
package co.ke.transunion.crbws.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControllerKenyaImplService", targetNamespace = "http://impl.ws.crbws.transunion.ke.co/", wsdlLocation = "https://secure3.transunionafrica.com/crbws/mobile/ke?wsdl")
public class ControllerKenyaImplService
    extends Service
{

    private final static URL CONTROLLERKENYAIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLLERKENYAIMPLSERVICE_EXCEPTION;
    private final static QName CONTROLLERKENYAIMPLSERVICE_QNAME = new QName("http://impl.ws.crbws.transunion.ke.co/", "ControllerKenyaImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://secure3.transunionafrica.com/crbws/mobile/ke?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLLERKENYAIMPLSERVICE_WSDL_LOCATION = url;
        CONTROLLERKENYAIMPLSERVICE_EXCEPTION = e;
    }

    public ControllerKenyaImplService() {
        super(__getWsdlLocation(), CONTROLLERKENYAIMPLSERVICE_QNAME);
    }

    public ControllerKenyaImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLLERKENYAIMPLSERVICE_QNAME, features);
    }

    public ControllerKenyaImplService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLLERKENYAIMPLSERVICE_QNAME);
    }

    public ControllerKenyaImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLLERKENYAIMPLSERVICE_QNAME, features);
    }

    public ControllerKenyaImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControllerKenyaImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControllerKenya
     */
    @WebEndpoint(name = "ControllerKenyaImplPort")
    public ControllerKenya getControllerKenyaImplPort() {
        return super.getPort(new QName("http://impl.ws.crbws.transunion.ke.co/", "ControllerKenyaImplPort"), ControllerKenya.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControllerKenya
     */
    @WebEndpoint(name = "ControllerKenyaImplPort")
    public ControllerKenya getControllerKenyaImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.crbws.transunion.ke.co/", "ControllerKenyaImplPort"), ControllerKenya.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLLERKENYAIMPLSERVICE_EXCEPTION!= null) {
            throw CONTROLLERKENYAIMPLSERVICE_EXCEPTION;
        }
        return CONTROLLERKENYAIMPLSERVICE_WSDL_LOCATION;
    }

}
